version: '3.9'
services:
  postgres:
    container_name: postgres_crypto
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_investment
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  investment:
    container_name: investment_crypto
    tty: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: investment_crypto
    env_file: .env
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: sekret1
      DJANGO_SUPERUSER_EMAIL: admin@example.com
    command: python /app/manage.py runserver 0.0.0.0:8080
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    links:
      - postgres:postgres
    depends_on:
      - postgres

volumes:
  web-static:
  pgdata:
