# Generated by Django 3.2.14 on 2022-08-02 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=19, verbose_name='Monto invertido (USD)')),
                ('amount_crypto', models.DecimalField(decimal_places=8, max_digits=19, verbose_name='Cantidad de cripto')),
                ('price_crypto', models.DecimalField(decimal_places=8, help_text='Precio al que se compro la cripto', max_digits=19, verbose_name='Precio de compra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inversión')),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_investment_crypto', to='crypto.crypto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_investment_user', to=settings.AUTH_USER_MODEL, verbose_name='Inversor')),
            ],
            options={
                'verbose_name': 'Inversiones',
                'verbose_name_plural': 'Inversiones',
                'db_table': 'tb_investments',
            },
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.DecimalField(decimal_places=4, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capital',
                'verbose_name_plural': 'Capitales',
                'db_table': 'tb_capital',
            },
        ),
    ]
