# Generated by Django 3.2.14 on 2022-08-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Activo financiero')),
                ('price', models.DecimalField(decimal_places=8, max_digits=19, verbose_name='Precio de mercado')),
                ('price_change', models.DecimalField(decimal_places=8, max_digits=19, verbose_name='Cambio 24h')),
                ('status', models.BooleanField(default=True, verbose_name='Activo?')),
                ('integration_binance', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Criptomoneda',
                'verbose_name_plural': 'Criptomonedas',
                'db_table': 'tb_crypto',
            },
        ),
    ]
