name: Deploy to Cloud Run in prod environment

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: ${{ secrets.GCP_SERVICE_NAME }}
  REGION: ${{ secrets.GCP_SERVICE_REGION }}

jobs:
  migrate:
    name: Migrate Database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get env file
        env:
          ENVIRONMENT: ${{ secrets.APP_ENV_PROD }}
        run: |
          cat <<EOF > .env
          "$ENVIRONMENT"
          EOF
          echo "cat .env"
          cat .env
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: migrate Database
        run: |
          python manage.py migrate
          exit 0;
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Create file environment
        env:
          ENVIRONMENT: ${{ secrets.APP_ENV_PROD }}
        run: |
          cat <<EOF > .env
          "$ENVIRONMENT"
          EOF
          echo "cat .env"
          cat .env
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: ./

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
